### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-acme#2]
Any blockers for a release? This issue is to request a 1.0.0, or at least a milestone

**Comment by zendern** [comment]
@jameskleeh Yup i think i finally have it in a place that i can do all verification http, tls and dns. So should be good for a release. Looks like my code is failing due to master micronaut-core failing to push out the latest version of http-server-netty where my dualProtocol change is. But I should be ready to release alongside 1.3 or shortly there after.

**Comment by jameskleeh** [comment]
@zendern Can you verify everything works with the 1.3.0.M1 release?

**Comment by zendern** [comment]
@jameskleeh 1.3.0.M1 looks to be good. I bumped to that version here 024c61bb4e999c9f770b5f9a1541d524c29e6b3e. Travis build is passing now and I have validated that the example application does all the things it should do. 

So what do next steps look like? We will need to get it into Maven so i need to start to get all that setup in travis? Or is the plan to pull it into `micronaut-projects` and reuse some of the setup you already have for the rest of the projects?

**Comment by jameskleeh** [comment]
@zendern If getting all of the setup done to get this published under your own group is too much to handle, I can move it to `micronaut-projects`. Let me know what you prefer

**Comment by zendern** [comment]
> @zendern If getting all of the setup done to get this published under your own group is too much to handle, I can move it to `micronaut-projects`. Let me know what you prefer

@jameskleeh I was waiting on it to be moved if we are being honest just b/c I thought that was the way it was planned to be structured. But that is really the only reason I have not moved forward with self publishing it. But I could go either way. Just let me know. If you want me to do the self publishing I can see what I can do to get it out there this weekend.

**Comment by fitzoh** [comment]
Graeme had [suggested](https://github.com/micronaut-projects/micronaut-core/issues/1117#issuecomment-471959719) moving it to `micronaut-projects` in the initial issue, and @zendern appears to be on board with migrating it, so unless there are objections I think it would probably make the most sense to move it now and ensure that artifacts are only published  under the `micronaut-projects` group ID

**Comment by zendern** [comment]
Just for visibility this is in progress. @jameskleeh moved the project yesterday and setup the keys so that we can publish via github actions. Currently having issue with the tests I have were it talks between host and the docker container for pebble when it runs in CI. Once those are solved should be pretty quick to get a real artifact out there.

**Comment by fitzoh** [comment]
Time to close this? https://github.com/micronaut-projects/micronaut-acme/releases/tag/v1.0.0
